<?php

return [
    'icons' => [
        ['name' => 'home', 'label' => 'Beranda'],
        ['name' => 'home-simple', 'label' => 'Beranda Simple'],
        ['name' => 'dashboard', 'label' => 'Dashboard'],
        ['name' => 'settings', 'label' => 'Pengaturan'],
        ['name' => 'user', 'label' => 'Pengguna'],
        ['name' => 'group', 'label' => 'Grup'],
        ['name' => 'shield', 'label' => 'Perisai / Role'],
        ['name' => 'view-grid', 'label' => 'Grid / Modul'],
        ['name' => 'database', 'label' => 'Database'],
        ['name' => 'folder', 'label' => 'Folder'],
        ['name' => 'page', 'label' => 'Halaman'],
        ['name' => 'app-window', 'label' => 'Aplikasi'],
        ['name' => 'bell', 'label' => 'Notifikasi'],
        ['name' => 'search', 'label' => 'Cari'],
        ['name' => 'plus', 'label' => 'Tambah'],
        ['name' => 'edit', 'label' => 'Edit'],
        ['name' => 'trash', 'label' => 'Hapus'],
        ['name' => 'eye', 'label' => 'Lihat'],
        ['name' => 'lock', 'label' => 'Kunci'],
        ['name' => 'key', 'label' => 'Kunci API'],
        ['name' => 'code', 'label' => 'Kode'],
        ['name' => 'cloud', 'label' => 'Cloud'],
        ['name' => 'globe', 'label' => 'Web'],
        ['name' => 'link', 'label' => 'Tautan'],
        ['name' => 'calendar', 'label' => 'Kalender'],
        ['name' => 'clock', 'label' => 'Jam'],
        ['name' => 'mail', 'label' => 'Email'],
        ['name' => 'phone', 'label' => 'Telepon'],
        ['name' => 'map-pin', 'label' => 'Lokasi'],
        ['name' => 'cart', 'label' => 'Keranjang'],
        ['name' => 'wallet', 'label' => 'Dompet'],
        ['name' => 'stats-report', 'label' => 'Laporan'],
        ['name' => 'graph-up', 'label' => 'Grafik Naik'],
        ['name' => 'graph-down', 'label' => 'Grafik Turun'],
        ['name' => 'media-image', 'label' => 'Gambar'],
        ['name' => 'media-image-list', 'label' => 'Galeri'],
        ['name' => 'book', 'label' => 'Buku'],
        ['name' => 'bookmark', 'label' => 'Bookmark'],
        ['name' => 'chat-bubble', 'label' => 'Chat'],
        ['name' => 'help-circle', 'label' => 'Bantuan'],
        ['name' => 'info-circle', 'label' => 'Info'],
        ['name' => 'warning-circle', 'label' => 'Peringatan'],
        ['name' => 'check-circle', 'label' => 'Sukses'],
        ['name' => 'xmark-circle', 'label' => 'Batal'],
        ['name' => 'menu', 'label' => 'Menu'],
        ['name' => 'sidebar-expand', 'label' => 'Sidebar'],
        ['name' => 'log-out', 'label' => 'Logout'],
        ['name' => 'refresh', 'label' => 'Refresh'],
        ['name' => 'download', 'label' => 'Unduh'],
        ['name' => 'upload', 'label' => 'Unggah'],
        ['name' => 'filter', 'label' => 'Filter'],
        ['name' => 'list', 'label' => 'Daftar'],
        ['name' => 'table', 'label' => 'Tabel'],
        ['name' => 'tools', 'label' => 'Tools'],
        ['name' => 'wrench', 'label' => 'Perbaikan'],
        ['name' => 'building', 'label' => 'Bangunan'],
        ['name' => 'city', 'label' => 'Kota'],
        ['name' => 'community', 'label' => 'Komunitas'],
        ['name' => 'shop', 'label' => 'Toko'],
        ['name' => 'delivery-truck', 'label' => 'Pengiriman'],
        ['name' => 'box', 'label' => 'Paket'],
        ['name' => 'label', 'label' => 'Label'],
        ['name' => 'tag', 'label' => 'Tag'],
        ['name' => 'star', 'label' => 'Bintang'],
        ['name' => 'heart', 'label' => 'Favorit'],
        ['name' => 'floppy-disk', 'label' => 'Simpan'],
        ['name' => 'printer', 'label' => 'Cetak'],
        ['name' => 'share-ios', 'label' => 'Bagikan'],
        ['name' => 'language', 'label' => 'Bahasa'],
        ['name' => 'translate', 'label' => 'Terjemahan'],
        ['name' => 'palette', 'label' => 'Warna'],
        ['name' => 'sparks', 'label' => 'Aksen'],
    ],
];
